# Generated by Django 3.2.8 on 2021-10-19 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0008_auto_20211019_1522'),
        ('Personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('totalSinImpuestos', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('totalDescuento', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('propina', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('importeTotal', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='DetallesFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=9)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DocumentosElectronicos.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
            ],
        ),
    ]
