# Generated by Django 3.2.8 on 2021-10-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentosElectronicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesfactura',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detallesfactura',
            name='precioUnitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detallesfactura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detallesfactura',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
