# Generated by Django 3.2.8 on 2021-10-28 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0011_alter_porcentajesimpuestos_options'),
        ('DocumentosElectronicos', '0002_auto_20211027_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Facturacion.empresa'),
        ),
    ]
