# Generated by Django 3.2.8 on 2021-10-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentosElectronicos', '0003_factura_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesfactura',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
