# Generated by Django 3.2.8 on 2021-10-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentosElectronicos', '0005_auto_20211028_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='clave_acceso',
            field=models.CharField(default='0', max_length=49),
        ),
    ]
