# Generated by Django 3.2.8 on 2021-10-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentosElectronicos', '0006_factura_clave_acceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='total',
        ),
    ]
