# Generated by Django 3.2.8 on 2021-10-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentosElectronicos', '0007_remove_factura_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.CharField(default='', max_length=100),
        ),
    ]
