# Generated by Django 3.2.8 on 2021-10-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentosElectronicos', '0008_factura_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='documento',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
