# Generated by Django 3.2.8 on 2021-11-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentosElectronicos', '0011_factura_mensajes'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='secuencial',
            field=models.CharField(default='000000000', max_length=9),
        ),
    ]
