# Generated by Django 3.2.8 on 2021-11-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentosElectronicos', '0012_factura_secuencial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='secuencial',
            field=models.CharField(default='000000000', max_length=9, unique=True),
        ),
    ]
