# Generated by Django 3.2.8 on 2021-11-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentosElectronicos', '0013_alter_factura_secuencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='firmado',
            field=models.BooleanField(default=False),
        ),
    ]
