# Generated by Django 3.2.8 on 2021-11-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentosElectronicos', '0014_factura_firmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
    ]
