# Generated by Django 3.2.8 on 2021-11-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentosElectronicos', '0015_factura_enviado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
