# Generated by Django 3.2.8 on 2021-11-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentosElectronicos', '0016_alter_factura_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='barcodes/'),
        ),
    ]
