# Generated by Django 3.2.8 on 2021-11-05 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentosElectronicos', '0017_factura_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='barcode',
        ),
    ]
