# Generated by Django 3.2.8 on 2021-11-09 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0023_datosfacturacion_usa_facturacion_electronica'),
        ('DocumentosElectronicos', '0018_remove_factura_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='impuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DocumentosElectronicos.factura')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facturacion.porcentajesimpuestos')),
            ],
        ),
    ]
