# Generated by Django 3.2.8 on 2021-11-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0023_datosfacturacion_usa_facturacion_electronica'),
        ('DocumentosElectronicos', '0019_impuestos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='impuestos',
            new_name='impuestosFactura',
        ),
    ]
