# Generated by Django 3.2.8 on 2021-11-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentosElectronicos', '0020_rename_impuestos_impuestosfactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='subtotal0',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
