# Generated by Django 3.2.8 on 2021-11-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentosElectronicos', '0021_factura_subtotal0'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='subtotalimpuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
