# Generated by Django 3.2.8 on 2022-02-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentosElectronicos', '0022_factura_subtotalimpuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='tipo',
            field=models.CharField(default='FACTURA', max_length=20),
        ),
    ]
