# Generated by Django 3.2.8 on 2022-02-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentosElectronicos', '0024_cuentacobrar_detallecuentascobrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecuentascobrar',
            name='no_abono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cuentacobrar',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
