# Generated by Django 3.2.8 on 2022-02-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentosElectronicos', '0026_detallecuentascobrar_por_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecuentascobrar',
            name='pago_no',
            field=models.IntegerField(default=0),
        ),
    ]
