# Generated by Django 3.2.8 on 2022-02-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentosElectronicos', '0027_detallecuentascobrar_pago_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecuentascobrar',
            name='saldo_anterior',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
