# Generated by Django 3.2.8 on 2022-02-27 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0027_datosfacturacion_secuencial_proforma'),
        ('DocumentosElectronicos', '0028_detallecuentascobrar_saldo_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='formaPago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Facturacion.formaspagos'),
        ),
    ]
