# Generated by Django 3.2.8 on 2022-03-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentosElectronicos', '0030_auto_20220303_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='ambiente',
            field=models.IntegerField(default=1),
        ),
    ]
