# Generated by Django 3.2.8 on 2022-04-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentosElectronicos', '0032_alter_factura_ambiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='ambiente',
            field=models.CharField(default='NO APLICA', max_length=40),
        ),
    ]
