# Generated by Django 3.2.8 on 2021-10-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13)),
                ('razon_social_nombres_apellidos', models.CharField(max_length=300)),
                ('nombre_comercial', models.CharField(blank=True, max_length=300, null=True)),
                ('direccion_establecimiento_matriz', models.CharField(max_length=300)),
                ('direccion_establecimiento_emisor', models.CharField(blank=True, max_length=300, null=True)),
                ('codigo_establecimiento_emisior', models.CharField(max_length=3)),
                ('punto_emision_establecimiento', models.CharField(max_length=3)),
                ('contribuyente_especial', models.CharField(blank=True, help_text='minimo 3, maximo 5', max_length=5, null=True)),
                ('obligado_llevar_contabilidad', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2)),
                ('logotipo', models.ImageField(upload_to='logotipo')),
                ('tipo_ambiente', models.CharField(default='1', max_length=1)),
                ('tipo_emision', models.CharField(default=1, max_length=1)),
            ],
        ),
    ]
