# Generated by Django 3.2.8 on 2021-10-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0002_alter_empresa_logotipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
