# Generated by Django 3.2.8 on 2021-10-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0005_datosfacturacion_impuestos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impuestos',
            options={'verbose_name_plural': '1. Codigos de Impuestos'},
        ),
    ]
