# Generated by Django 3.2.8 on 2021-10-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0007_porcentajesimpuestos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porcentajesimpuestos',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
