# Generated by Django 3.2.8 on 2021-10-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0008_alter_porcentajesimpuestos_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='porcentajesimpuestos',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
