# Generated by Django 3.2.8 on 2021-10-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0009_porcentajesimpuestos_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='porcentajesimpuestos',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
