# Generated by Django 3.2.8 on 2021-10-19 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0010_porcentajesimpuestos_porcentaje'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porcentajesimpuestos',
            options={'verbose_name_plural': '1.1 Porcentajes de Impuestos'},
        ),
    ]
