# Generated by Django 3.2.8 on 2021-10-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0011_alter_porcentajesimpuestos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ambiente', models.CharField(default=1, max_length=1)),
                ('webservice', models.TextField()),
            ],
        ),
    ]
