# Generated by Django 3.2.8 on 2021-10-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0012_webservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='tipo_ambiente',
        ),
        migrations.AddField(
            model_name='webservices',
            name='estado',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='webservices',
            name='tipo_ambiente',
            field=models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], default=1, max_length=1),
        ),
    ]
