# Generated by Django 3.2.8 on 2021-10-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0013_auto_20211028_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webservices',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
