# Generated by Django 3.2.8 on 2021-10-28 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0014_alter_webservices_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='webservices',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Facturacion.empresa'),
        ),
    ]
