# Generated by Django 3.2.8 on 2021-10-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0015_webservices_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosfacturacion',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados'),
        ),
        migrations.AddField(
            model_name='datosfacturacion',
            name='clave',
            field=models.CharField(default='', max_length=100),
        ),
    ]
