# Generated by Django 3.2.8 on 2021-10-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0016_auto_20211028_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormasPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('codigo', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '1. Codigos de Impuestos',
            },
        ),
        migrations.AlterModelOptions(
            name='datosfacturacion',
            options={'verbose_name_plural': '5. Porcentajes de Impuestos'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name_plural': '4. Empresa'},
        ),
        migrations.AlterModelOptions(
            name='impuestos',
            options={'verbose_name_plural': '2. Codigos de Impuestos'},
        ),
        migrations.AlterModelOptions(
            name='porcentajesimpuestos',
            options={'verbose_name_plural': '2.1 Porcentajes de Impuestos'},
        ),
        migrations.AlterModelOptions(
            name='webservices',
            options={'verbose_name_plural': '3. Webservices'},
        ),
    ]
