# Generated by Django 3.2.8 on 2021-10-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0017_auto_20211028_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formaspagos',
            options={'verbose_name_plural': '1. Formas de Pago'},
        ),
        migrations.AlterField(
            model_name='formaspagos',
            name='codigo',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
