# Generated by Django 3.2.8 on 2021-10-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0018_auto_20211028_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formaspagos',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
