# Generated by Django 3.2.8 on 2021-10-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0019_alter_formaspagos_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='webservices',
            name='envio_consulta',
            field=models.IntegerField(default=1, help_text='1 para enviar al sri, 2 para consultar'),
        ),
    ]
