# Generated by Django 3.2.8 on 2021-10-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0020_webservices_envio_consulta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosfacturacion',
            options={'verbose_name_plural': '5. Datos de la Facturación'},
        ),
    ]
