# Generated by Django 3.2.8 on 2021-11-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0022_datosfacturacion_ambiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosfacturacion',
            name='usa_facturacion_electronica',
            field=models.BooleanField(default=False),
        ),
    ]
