# Generated by Django 3.2.8 on 2021-11-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0023_datosfacturacion_usa_facturacion_electronica'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosfacturacion',
            name='ruta_home_media',
            field=models.CharField(default='/home/johnny/media/', max_length=1000),
        ),
    ]
