# Generated by Django 3.2.8 on 2021-11-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0024_datosfacturacion_ruta_home_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosfacturacion',
            name='secual_orden_trabajo',
            field=models.IntegerField(default=0),
        ),
    ]
