# Generated by Django 3.2.8 on 2022-02-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0025_datosfacturacion_secual_orden_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosfacturacion',
            name='secual_orden_trabajo',
            field=models.IntegerField(default=1),
        ),
    ]
