# Generated by Django 3.2.8 on 2022-02-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0027_datosfacturacion_secuencial_proforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='formaspagos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
