# Generated by Django 3.2.8 on 2022-02-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0028_formaspagos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='encabezado',
            field=models.ImageField(blank=True, null=True, upload_to='encabezado'),
        ),
    ]
