# Generated by Django 3.2.8 on 2022-04-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0032_auto_20220418_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webservices',
            name='tipo_ambiente',
            field=models.IntegerField(choices=[(1, 'PRUEBAS'), (2, 'PRODUCCIÓN')], default=1),
        ),
    ]
