# Generated by Django 3.2.8 on 2021-11-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdenesTrabajo', '0002_auto_20211112_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='hora_fecha_salida',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='secuencial',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
