# Generated by Django 3.2.8 on 2021-10-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoAuxiliar', models.CharField(blank=True, max_length=25, null=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.IntegerField(default=1)),
                ('precioUnitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('precioTotalSinImpuesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
        ),
    ]
