# Generated by Django 3.2.8 on 2021-10-18 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0008_alter_porcentajesimpuestos_nombre'),
        ('Productos', '0002_producto_impuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='impuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Facturacion.porcentajesimpuestos'),
        ),
    ]
