# Generated by Django 3.2.8 on 2021-10-19 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_auto_20211019_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precioTotalSinImpuesto',
        ),
    ]
