# Generated by Django 3.2.8 on 2021-10-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_remove_producto_preciototalsinimpuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('S', 'Servicios'), ('P', 'Productos')], default=1, max_length=12),
            preserve_default=False,
        ),
    ]
