# Generated by Django 3.2.8 on 2021-10-19 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0007_kardex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kardex',
            options={'verbose_name_plural': '1.1 Kardex'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name_plural': '1. Productos'},
        ),
    ]
